Repository jump-dev/JuMP.jl, pull requests merged in 2021-03, with the labels that each got.

#2499 Add logistic regression tutorial from JuMPTutorials
  docs/make.jl
  docs/src/tutorials/Conic programs/logistic_regression.jl
Labels: docs

#2518 [docs] Clarify warning in Nonlinear Modeling
  docs/src/manual/nlp.md
Labels: docs

#2519 [docs] Fix typo in callbacks
  docs/src/manual/callbacks.md
Labels: Type: Documentation

#2515 Improve performance of value(NonlinearExpression)
  src/_Derivatives/forward.jl
  src/_Derivatives/subexpressions.jl
  src/nlp.jl
Labels: Type: Performance

#2466 First pass at a feasibility checker.
  docs/src/manual/solutions.md
  docs/src/reference/solutions.md
  src/JuMP.jl
  src/feasibility_checker.jl
  test/feasibility_checker.jl
Labels: Status: Needs review

#2484 Add precompilation directives
  src/JuMP.jl
  src/precompile.jl
Labels: Type: Performance

#2525 [docs] update roadmap
  docs/src/developers/roadmap.md
Labels: Type: Documentation

#2524 Allow slicing of DenseAxisArray
  src/Containers/DenseAxisArray.jl
  test/Containers/DenseAxisArray.jl
Labels: Category: Containers, Type: Performance

#2530 [docs] Add performance tips
  docs/src/tutorials/Getting started/performance_tips.jl
Labels: Type: Documentation

#2531 Refactor MIP tips and tricks
  docs/src/tutorials/Mixed-integer linear programs/tips_and_tricks.jl
  docs/src/tutorials/Optimization concepts/integer_programming.jl
Labels: Type: Documentation

#2532 [docs] refactor conic tips and tricks
  docs/src/tutorials/Conic programs/tips_and_tricks.jl
Labels: Type: Documentation

#2534 Expand norm() error message
  src/sets.jl
Labels: Type: Error Messages

#2536 Improve the error message for unsupported functions
  src/_Derivatives/forward.jl
  test/nlp.jl
Labels: Category: Nonlinear, Type: Error Messages

#2449 Refactor printing to reduce content printed in IJulia mode
  docs/src/manual/models.md
  docs/src/reference/models.md
  docs/src/tutorials/Optimization concepts/benders_decomposition.jl
  docs/src/tutorials/Optimization concepts/benders_lazy_constraints.jl
  src/print.jl
  test/print.jl
Labels: Category: Printing, Status: Needs developer call, Status: Needs review

#2528 Support copying containers
  src/copy.jl
  test/model.jl
Labels: Category: Containers, Type: Bug

#2527 Support AbstractArray in DenseAxisArray constructor
  src/Containers/DenseAxisArray.jl
  test/Containers/DenseAxisArray.jl
Labels: Category: Containers, Type: Bug

#2544 Restore multiline LaTeX
  docs/Project.toml
  docs/src/manual/models.md
  src/print.jl
  test/print.jl
Labels: Category: Printing

#2543 Improve error message and add warning when re-registering a function
  docs/src/manual/nlp.md
  src/_Derivatives/types.jl
  test/nlp.jl
Labels: Category: Nonlinear, Type: Documentation, Type: Error Messages

#2542 Add JuliaFormatter to the style guide
  .github/workflows/format_check.yml
  docs/src/developers/style.md
Labels: Type: Documentation

#2547 Add more docstrings
  src/JuMP.jl
  src/aff_expr.jl
  src/constraints.jl
  src/macros.jl
  src/print.jl
  src/quad_expr.jl
  src/sets.jl
  src/variables.jl
Labels: Type: Documentation

#2551 Add set_start_value(x, ::Nothing)
  src/variables.jl
  test/variable.jl
Labels: Type: Bug
