Repository jump-dev/JuMP.jl, pull requests merged in 2021-10, with the labels that each got.

#2719 [breaking] Add anonymous NLparameters and registered named parameters
  docs/src/manual/nlp.md
  docs/src/tutorials/Conic programs/logistic_regression.jl
  src/macros.jl
  test/macros.jl
  test/print.jl
Labels: Category: Nonlinear, Category: Internals, breaking

#2728 Improve error message for invalidly named containers
  src/Containers/macro.jl
  src/macros.jl
  test/macros.jl
Labels: Type: Error Messages

#2657 Add vector of scalar variables with `in` syntax
  src/Containers/DenseAxisArray.jl
  src/macros.jl
  src/variables.jl
  test/macros.jl
Labels: Category: Modeling

#2731 [breaking] Make moi_xxx functions private
  src/JuMP.jl
  src/constraints.jl
  src/precompile.jl
  src/variables.jl
Labels: breaking

#2729 Add error message for variable comparison with number
  src/variables.jl
  test/variable.jl
Labels: Type: Error Messages

#2732 [breaking] Deprecate SDconstraint and add new syntax for PSDCone constraints
  docs/src/manual/constraints.md
  docs/src/reference/constraints.md
  docs/src/tutorials/Semidefinite programs/experiment_design.jl
  docs/src/tutorials/Semidefinite programs/min_ellipse.jl
  docs/src/tutorials/Semidefinite programs/robust_uncertainty.jl
  src/macros.jl
  src/sd.jl
  test/constraint.jl
Labels: Category: Modeling, breaking

#2785 [docs] edit models.jl
  docs/src/manual/models.md
Labels: Type: Documentation
