Repository jump-dev/JuMP.jl, pull requests merged in 2021-05, with the labels that each got.

#2574 Enhance extendibility of constraint macros
  docs/src/developers/extensions.md
  src/macros.jl
  test/constraint.jl
  test/macros.jl
Labels: Category: Internals, Type: Enhancement

#2570 Allow overloading of container types
  docs/src/manual/containers.md
  src/Containers/container.jl
  src/Containers/macro.jl
  test/Containers/macro.jl
  test/macros.jl
Labels: Category: Containers

#2600 Simplify documentation for SOS
  docs/src/manual/constraints.md
Labels: Type: Documentation

#2603 Mention latency in performance tips
  docs/src/tutorials/Getting started/performance_tips.jl
Labels: Type: Documentation

#2602 Mention solver-dependent callbacks
  docs/src/background/should_i_use.md
  docs/src/manual/callbacks.md
  docs/src/tutorials/Mixed-integer linear programs/callbacks.jl
Labels: Type: Documentation

#2601 Clarify that delete does not call unregister
  docs/src/index.md
  docs/src/manual/constraints.md
  docs/src/manual/variables.md
  src/constraints.jl
  src/variables.jl
Labels: Type: Documentation

#2608 Fix documentation by adding ndims(::AbstractJuMPScalar)
  src/JuMP.jl
  src/quad_expr.jl
Labels: Type: Bug
