Repository jump-dev/JuMP.jl, pull requests merged in 2021-06, with the labels that each got.

#2584 Update the JuMP logo to match modern Julia
  README.md
  docs/make.jl
  docs/src/assets/extra_styles.css
  docs/src/assets/jump-logo-with-text.svg
  docs/src/assets/logo-dark-with-text.svg
  docs/src/assets/logo-dark.svg
  docs/src/assets/logo-with-text-background.svg
  docs/src/assets/logo-with-text.svg
  docs/src/assets/logo.png
  docs/src/assets/logo.svg
  docs/src/index.md
Labels: Type: Documentation

#2621 Fix map for DenseAxisArray with OneTo axes
  src/Containers/DenseAxisArray.jl
  test/Containers/DenseAxisArray.jl
Labels: Type: Bug

#2630 Update printing of SparseAxisArray
  docs/src/manual/containers.md
  docs/src/manual/variables.md
  src/Containers/SparseAxisArray.jl
  test/Containers/SparseAxisArray.jl
Labels: Category: Containers

#2632 Update to documenter 0.27
  docs/Project.toml
Labels: Type: Documentation
