Repository jump-dev/JuMP.jl, pull requests merged in 2022-09, with the labels that each got.

#3064 [Containers] fix DenseAxisArray with Vector key
  src/Containers/DenseAxisArray.jl
  test/Containers/DenseAxisArray.jl
Labels: Type: Bug, Category: Containers

#3065 [docs] update docs/Project.toml
  docs/Project.toml
  docs/make.jl
Labels: Type: Documentation

#3068 [docs] add more examples to nlp.md
  docs/src/manual/nlp.md
Labels: Category: Nonlinear, Type: Documentation

#3043 [docs] start a tutorial on debugging JuMP models
  docs/make.jl
  docs/src/tutorials/getting_started/debugging.jl
Labels: Type: Documentation

#3073 [docs] improve factory scheduling example
  docs/src/tutorials/linear/factory_schedule.jl
  docs/src/tutorials/linear/factory_schedule_demand.txt
  docs/src/tutorials/linear/factory_schedule_factories.txt
Labels: Type: Documentation

#3075 [docs] override style in PDF output
  docs/src/assets/custom.sty
Labels: Type: Documentation

#3074 [docs] update NLP docs and explain performance issue
  docs/src/manual/nlp.md
Labels: Category: Nonlinear, Type: Documentation

#3076 [docs] add link to documentation PDF
  docs/src/index.md
Labels: Type: Documentation

#3078 [docs] lots of minor tweaks to the tutorials after reading through the PDF
  docs/make.jl
  docs/src/tutorials/getting_started/getting_started_with_data_and_plotting.jl
  docs/src/tutorials/linear/cannery.jl
  docs/src/tutorials/linear/diet.jl
  docs/src/tutorials/linear/facility_location.jl
  docs/src/tutorials/linear/factory_schedule.jl
  docs/src/tutorials/linear/geographic_clustering.jl
  docs/src/tutorials/linear/network_flows.jl
  docs/src/tutorials/linear/sudoku.jl
  docs/src/tutorials/nonlinear/rocket_control.jl
  docs/src/tutorials/nonlinear/space_shuttle_reentry_trajectory.jl
Labels: Type: Documentation

#3077 [docs] change Getting started with Julia to use REPL blocks
  docs/make.jl
  docs/src/tutorials/getting_started/getting_started_with_julia.jl
Labels: Type: Documentation

#3081 [docs] remove urban_plan.jl
  docs/make.jl
  docs/src/tutorials/linear/urban_plan.jl
Labels: Type: Documentation

#3082 [docs] refactor the transportation problem tutorial
  docs/.gitignore
  docs/src/tutorials/linear/transp.jl
Labels: Type: Documentation

#3084 [docs] condense the simple nonlinear tutorials into a single page
  docs/make.jl
  docs/src/tutorials/nonlinear/clnlbeam.jl
  docs/src/tutorials/nonlinear/mle.jl
  docs/src/tutorials/nonlinear/qcp.jl
  docs/src/tutorials/nonlinear/rosenbrock.jl
  docs/src/tutorials/nonlinear/simple_examples.jl
Labels: Type: Documentation

#3080 [docs] add Vale as a documentation linter
  .github/workflows/documentation.yml
  docs/.vale.ini
  docs/Project.toml
  docs/src/developers/extensions.md
  docs/src/developers/roadmap.md
  docs/src/tutorials/algorithms/tsp_lazy_constraints.jl
  docs/src/tutorials/applications/power_systems.jl
  docs/src/tutorials/conic/experiment_design.jl
  docs/src/tutorials/conic/max_cut_sdp.jl
  docs/src/tutorials/conic/min_ellipse.jl
  docs/src/tutorials/getting_started/getting_started_with_data_and_plotting.jl
  docs/src/tutorials/getting_started/getting_started_with_sets_and_indexing.jl
  docs/src/tutorials/linear/facility_location.jl
  docs/src/tutorials/linear/lp_sensitivity.jl
  docs/src/tutorials/nonlinear/space_shuttle_reentry_trajectory.jl
  docs/src/tutorials/nonlinear/tips_and_tricks.jl
  docs/styles/Vocab/JuMP-Vocab/accept.txt
Labels: Type: Documentation

#3089 [docs] Tidy the min_ellipse tutorial
  docs/src/tutorials/conic/min_ellipse.jl
Labels: Type: Documentation

#3091 Fix empty sums in Aff/QuadExpr parse_expression
  src/nlp.jl
  test/nlp.jl
Labels: Type: Bug, Category: Nonlinear

#3098 [docs] update multi.jl tutorial to use an SQLite database
  docs/Project.toml
  docs/src/tutorials/linear/multi.jl
  docs/src/tutorials/linear/multi.sqlite
Labels: Type: Documentation

#3088 Pass names (index_vars) to container extensions.
  src/Containers/container.jl
  src/Containers/macro.jl
  test/Containers/macro.jl
Labels: Type: Enhancement, Category: Containers
