Repository jump-dev/JuMP.jl, pull requests merged in 2023-02, with the labels that each got.

#3210 [docs] fix version links in changelog
  docs/src/changelog.md
Labels: Type: Documentation

#3213 [docs] tweak diet.jl tutorial to use more DataFrame logic
  docs/src/tutorials/linear/diet.jl
Labels: Type: Documentation

#3226 Fix init kwarg in nonlinear generator expressions
  src/macros.jl
  test/test_macros.jl
Labels: Type: Bug

#3230 [docs] fix typo in network_flows.jl
  docs/src/tutorials/linear/network_flows.jl
Labels: Type: Documentation

#3229 [docs] refactor some conic tutorials into simple_examples.jl
  docs/make.jl
  docs/src/tutorials/conic/cluster.jl
  docs/src/tutorials/conic/corr_sdp.jl
  docs/src/tutorials/conic/max_cut_sdp.jl
  docs/src/tutorials/conic/min_distortion.jl
  docs/src/tutorials/conic/robust_uncertainty.jl
  docs/src/tutorials/conic/simple_examples.jl
Labels: Type: Documentation

#3227 [docs] add multiobjective portfolio example
  docs/Project.toml
  docs/src/tutorials/nonlinear/introduction.md
  docs/src/tutorials/nonlinear/portfolio.jl
Labels: Type: Documentation

#3231 [docs] add tutorial on parallelism
  docs/.gitignore
  docs/make.jl
  docs/src/tutorials/algorithms/parallelism.md
Labels: Type: Documentation

#3240 [docs] fix thread safefy issue in parallelism tutorial
  docs/src/tutorials/algorithms/parallelism.md
Labels: Type: Bug, Type: Documentation

#3244 Fix dot between JuMP types and constant
  src/operators.jl
  test/test_complex.jl
Labels: Type: Bug

#3241 [docs] clarify that matrix must be Hermitian
  docs/src/manual/complex.md
Labels: Type: Documentation
